---
- hosts: azure
  become: yes
  remote_user: azureuser
  become_method: sudo

  tasks:

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install docker-compose
    get_url: 
      url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: '+x'

  - name: enable Docker services
    service:
      name: "docker"
      state: started
      enabled: yes
    register: service_output

  - name: Docker service status
    debug: var=service_output
  
  - name: Add current user to Docker group
    command: usermod -aG docker azureuser
    become: yes
  
  - name: Clone Git repository
  git:
    repo: https://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@github.com/husseinahmed-dev/LS-Lab2.git
    dest: ~/
    update: yes

  - name: Change into src directory
    become: yes
    command: cd ~/LS-Lab2/src

  - name: Run docker-compose up
    become: yes
    command: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d